name: conch
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.16.0=h6cf1ce9_1008
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h0708190_1
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - icu=68.2=h9c3ff4c_0
  - imageio=2.37.0=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lazy_loader=0.4=py310h06a4308_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=2.2.1=h9c3ff4c_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.68.4=h174f98d_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.9.12=h72842e0_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=py310h06a4308_0
  - nmslib=2.1.1=py310hc4a4660_1
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openjpeg=2.4.0=hb52868f_1
  - openslide=3.4.1=h978ee9a_4
  - openslide-python=1.1.2=py310h5764c6d_5
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py310h06a4308_0
  - pcre=8.45=h9c3ff4c_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h7934f7d_0
  - prettytable=3.5.0=py310h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11=2.13.6=py310hdb19cb5_1
  - pybind11-global=2.13.6=py310hdb19cb5_1
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - scikit-image=0.25.2=py310hc74f9fe_0
  - scipy=1.15.3=py310h525edd1_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - tbb-devel=2021.8.0=hdb19cb5_0
  - tensorboardx=2.6.2.2=py310h06a4308_0
  - tifffile=2025.2.18=py310h06a4308_0
  - tk=8.6.14=h993c535_1
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alembic==1.16.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - colorlog==6.9.0
      - conch==0.1.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - early-stopping-pytorch==1.0.10
      - einops==0.8.1
      - einops-exts==0.0.4
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - ftfy==6.3.1
      - future==1.0.0
      - grad-cam==1.5.5
      - greenlet==3.2.4
      - grpcio==1.74.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - idna==3.10
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - mako==1.3.10
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - multidict==6.6.4
      - opencv-python==4.12.0.88
      - optuna==4.5.0
      - pandas==2.3.1
      - pillow==11.3.0
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.1.0
      - ptflops==0.7.5
      - pyg-lib==0.4.0+pt27cu126
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - six==1.17.0
      - sqlalchemy==2.0.43
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==1.0.17
      - tokenizers==0.21.2
      - tomli==2.2.1
      - torch-cluster==1.6.3+pt27cu126
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt27cu126
      - torch-sparse==0.6.18+pt27cu126
      - torch-spline-conv==1.2.2+pt27cu126
      - torchmetrics==1.8.2
      - torchsurv==0.1.5
      - tqdm==4.67.1
      - transformers==4.53.3
      - ttach==0.0.3
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - yarl==1.20.1
prefix: /home/server/anaconda3/envs/conch
